# Copyright (C) 2023  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Which Docker image shall be used on the GitLab runner?
image: docker:26

# Details about how to connect to the Docker service to run this build.
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:26-dind

stages:
  - build
  - deploy

# Display information before we start the build.
before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# This section describes what shall be done to build and test the project.
build-and-test:
  tags:
    - docker-build
  stage: build
  script:
    - docker build . --output . --target copytohost
  except:
    - tags
  coverage: '/Total:\|\s?(\d+\.?\d*%)/'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

# This section describes what shall be done to deploy artifacts from the project.
release:
  # This runs only when we have a push to a branch that has a tag (it's a release), the tag must follow the semantic versioning
  # should only run when the branch is tested successfully
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+/ # This is a regular expression that matches semantic versioning
  
  tags:
    - docker-build
  
  stage: deploy
  # This job depends on the build-and-test job.
  # Will only run if the build-and-test job is successful.
  dependencies:
    - build-and-test
  
  script:
    - docker build -f Dockerfile -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"